-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 25, 2018 at 08:24 PM
-- Server version: 10.1.30-MariaDB
-- PHP Version: 7.2.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bookrental`
--

-- --------------------------------------------------------

--
-- Table structure for table `book_details`
--

CREATE TABLE `book_details` (
  `B_ID` int(11) NOT NULL,
  `B_ISBN` varchar(50) NOT NULL,
  `B_TITLE` varchar(100) NOT NULL,
  `B_GENRE` varchar(50) NOT NULL,
  `B_AUTHOR` varchar(50) NOT NULL,
  `B_PUBLISHER` varchar(50) NOT NULL,
  `B_DESC` text NOT NULL,
  `B_PRICE` double NOT NULL,
  `B_QTY` int(11) NOT NULL,
  `B_REGISTERED` date NOT NULL,
  `B_PUBLISHED` date NOT NULL,
  `B_IMG` varchar(50) NOT NULL,
  `B_OTHER` text NOT NULL,
  `RENT_COUNT` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `book_details`
--

INSERT INTO `book_details` (`B_ID`, `B_ISBN`, `B_TITLE`, `B_GENRE`, `B_AUTHOR`, `B_PUBLISHER`, `B_DESC`, `B_PRICE`, `B_QTY`, `B_REGISTERED`, `B_PUBLISHED`, `B_IMG`, `B_OTHER`, `RENT_COUNT`) VALUES
(1, '9781451669411', 'Hamlet', 'Drama', 'William Shakespeare', 'Simon & Schuster', 'Among them: What is the Ghostâ€”Hamletâ€™s father demanding justice, a tempting demon, an angelic messenger? Does Hamlet go mad, or merely pretend to? Once he is sure that Claudius is a murderer, why does he not act? Was his mother, Gertrude, unfaithful to her husband or complicit in his mu\r\n', 10, 3, '2018-05-18', '2012-01-04', 'images/1.jpg', 'Hamlet is Shakespeareâ€™s most popular, and most puzzling, play. It follows the form of a â€œrevenge tragedy,â€ in which the hero, Hamlet, seeks vengeance against his fatherâ€™s murderer, his uncle Claudius, now the king of Denmark. Much of its fascination, however, lies in its uncertainties.', 0),
(2, '9781451694727', 'Macbeth', 'Drama', 'William Shakespeare', 'Simon & Schuster', 'Like other plays, Macbeth speaks to each generation. Its story was once seen as that of a hero who commits an evil act and pays an enormous price. Recently, it has been applied to nations that overreach themselves and to modern alienation. The line is blurred between Macbethâ€™s evil and his opponentsâ€™ good, and there are new attitudes toward both witchcraft and gender.', 10, 5, '2018-05-18', '2012-01-04', 'images/2.jpg', 'In 1603, James VI of Scotland ascended the English throne, becoming James I of England. London was alive with an interest in all things Scottish, and Shakespeare turned to Scottish history for material. He found a spectacle of violence and stories of traitors advised by witches and wizards, echoing Jamesâ€™s belief in a connection between treason and witchcraft.\r\n\r\nIn depicting a man who murders to become king, Macbeth teases us with huge questions. Is Macbeth tempted by fate, or by his or his wifeâ€™s ambition? Why does their success turn to ashes?', 0),
(3, '9781451621709', 'Romeo and Juliet', 'Drama', 'William Shakespeare', 'Simon & Schuster', 'In this death-filled setting, the movement from love at first sight to the loversâ€™ final union in death seems almost inevitable. And yet, this play set in an extraordinary world has become the quintessential story of young love. In part because of its exquisite language, it is easy to respond as if it were about all young lovers.\r\n', 10, 9, '2018-05-18', '2011-08-01', 'images/3.jpg', 'In Romeo and Juliet, Shakespeare creates a violent world, in which two young people fall in love. It is not simply that their families disapprove; the Montagues and the Capulets are engaged in a blood feud.', 0),
(4, '9780525478812', 'The Fault in Our Stars', 'Drama', 'John Green', 'Dutton Juvenile', 'A match made at cancer kid support group, Augustus is gorgeous, in remission, and shockingly, to her interested in Hazel. Being with Augustus is both an unexpected destination and a long-needed journey, pushing Hazel to re-examine how sickness and health, life and death, will define her and the legacy that everyone leaves behind. ', 9, 4, '2018-05-18', '2012-01-10', 'images/4.jpg', 'Diagnosed with Stage IV thyroid cancer at 12, Hazel was prepared to die until, at 14, a medical miracle shrunk the tumours in her lungs... for now. Two years post-miracle, sixteen-year-old Hazel is post-everything else, too post-high school, post-friends and post-normalcy. And even though she could live for a long time (whatever that means) Hazel lives tethered to an oxygen tank, the tumours tenuously kept at bay with a constant chemical assault. Enter Augustus Waters.', 0),
(5, '9781853260957', 'King Lear', 'Drama', 'William Shakespeare', 'Wordsworth Editions Ltd', 'King Lear has been widely acclaimed as Shakespeare\'s most powerful tragedy. Elemental and passionate, it encompasses the horrific and the heart-rending. Love and hate, loyalty and treachery, cruelty and self-sacrifice: all these contend in a tempestuous drama which has become an enduring classic of the world\'s literature. In the theatre and on screen King Lear continues to challenge and enthral.\r\n', 9, 4, '2018-05-18', '1997-08-01', 'images/6.jpg', 'It depicts the gradual descent into madness of the title character, after he disposes of his kingdom giving bequests to two of his three daughters based on their flattery of him, bringing tragic consequences for all.', 0),
(6, '9780141328294', 'Thirteen Reasons Why', 'Drama', 'Jay Asher', 'Penguin Books Ltd', 'You can\'t stop the future. You can\'t rewind the past. The only way to learn the secret . . . is to press play.', 19, 3, '2018-05-18', '2010-07-01', 'images/7.jpg', 'The story of a young high school student as she descends into despair brought on by betrayal and bullying, culminating with her suicide.', 0),
(7, '9780060512637', 'Our Town', 'Drama', 'Thornton Wilder', 'HarperCollins Publishers Inc', 'Our Town was first produced and published in 1938 to wide acclaim. This Pulitzer Prize-winning drama of life in the small village of Grover\'s Corners, an allegorical representation of all life, has become a classic. It is Thornton Wilder\'s most renowned and most frequently performed play. ', 22, 7, '2018-05-18', '2011-09-06', 'images/7.jpg', 'It tells the story of the fictional American small town of Grover\'s Corners between 1901 and 1913 through the everyday lives of its citizens.', 0),
(8, '9780099464464', 'The Time Travelers Wife', 'Drama', 'Audrey Niffenegger', 'Vintage Publishing', 'Published in 2003, the novel garnered several book awards and has become an international bestseller.', 31, 4, '2018-05-18', '2010-03-01', 'images/8.jpg', 'This is the extraordinary love story of Clare and Henry who met when Clare was six and Henry was thirty-six, and were married when Clare was twenty-two and Henry thirty. Impossible but true, because Henry suffers from a rare condition where his genetic clock periodically resets and he finds himself pulled suddenly into his past or future. In the face of this force they can neither prevent nor control, Henry and Clare\'s struggle to lead normal lives is both intensely moving and entirely unforgettable. ', 0),
(9, '9780747585893', 'A Thousand Splendid Suns', 'Drama', 'Khaled Hosseini', 'Bloomsbury Publishing PLC', ' Thousand Splendid Suns went back to press almost daily its first week on sale, building to 1,255,000 copies in print in the U.S. Rolling into its second week, the book continued to fly out of stores, with another 150,000 more copies printed. ', 29, 2, '2018-05-18', '2008-10-01', 'images/9.jpg', 'Mariam is only fifteen when she is sent to Kabul to marry Rasheed. Nearly two decades later, a friendship grows between Mariam and a local teenager, Laila, as strong as the ties between mother and daughter. When the Taliban take over, life becomes a desperate struggle against starvation, brutality and fear. Yet love can move a person to act in unexpected ways, and lead them to overcome the most daunting obstacles with a startling heroism. ', 0),
(10, '9781408824863', 'The Kite Runner', 'Drama', 'Khaled Hosseini', 'Bloomsbury Publishing PLC', 'The Kite Runner became a bestseller after being printed in paperback and was popularized in book clubs. It was a number one New York Times bestseller for over two years, with over seven million copies sold in the United States.', 22, 1, '2018-05-18', '2011-09-05', 'images/10.jpg', 'Afghanistan, 1975: Twelve-year-old Amir is desperate to win the local kite-fighting tournament and his loyal friend Hassan promises to help him. But neither of the boys can foresee what will happen to Hassan that afternoon, an event that is to shatter their lives. After the Russians invade and the family is forced to flee to America, Amir realises that one day he must return to Afghanistan under Taliban rule to find the one thing that his new world cannot grant him: redemption. ', 0),
(11, '9781444707861', 'It', 'Horror', 'Stephen King', 'Hodder & Stoughton General Division', 'NOW A MAJOR MOTION PICTURE - Stephen King\'s terrifying classic.\r\n\r\n\'They float...and when you\'re down here with me, you\'ll float, too.\'\r\n', 40, 9, '2018-05-18', '2011-06-26', 'images/11.jpg', 'The story follows the exploits of seven children as they are terrorized by the eponymous being, which exploits the fears and phobias of its victims in order to disguise itself while hunting its prey. \"It\" primarily appears in the form of a clown in order to attract its preferred prey of young children.', 0),
(12, '9781501104237', 'Little Heaven', 'Horror', 'Nick Cutter', 'Gallery Books', 'A \"gripping and terrifying story...and one not to be missed\" (Robert McCammon) from the acclaimed author of The Troop and The Deep!\r\n\r\nNick Cutter ups his game every time. Beautifully written--menace drips from every page.\" --Seanan McGuire, New York Times bestselling author', 17, 6, '2018-05-18', '2017-07-11', 'images/12.jpg', 'A trio of mismatched mercenaries--Micah Shughrue, Minerva Atwater, and Ebenzer Elkins, colloquially known as \"the Englishman\"--is hired by young Ellen Bellhaven for a deceptively simple task: check in on her nephew, who may have been taken against his will to a remote New Mexico backwoods settlement called Little Heaven, where a clandestine religious cult holds sway. But shortly after they arrive, things begin to turn ominous. There are stirrings in the woods and over the treetops--and above all else, the brooding shape of a monolith known as the Black Rock casts its terrible pall. Paranoia and distrust soon grip the settlement. Escape routes are gradually cut off as events spiral toward madness. Hell--or the closest thing to it--invades Little Heaven.', 0),
(13, '9780375703768', 'House of Leaves', 'Horror', 'Mark Z. Danielewski', 'Random House USA Inc', 'Years ago, when House of Leaves was first being passed around, it was nothing more than a badly bundled heap of paper, parts of which would occasionally surface on the Internet. No one could have anticipated the small but devoted following this terrifying story would soon command.', 39, 2, '2018-05-18', '2000-04-10', 'images/13.jpg', '-	A tattoo artist named Johnny Truant discovers the manuscript for an academic study on a documentary film called The Navidson Record, about a Virginia farmhouse with a curious anomaly: the internal measurements of the home are larger than the external ones. While reading and annotating the manuscript, Johnny descends into a madness of unclear origins.', 0),
(14, '9780552166775', 'The Exorcist', 'Horror', 'William Peter Blatty', 'Transworld Publishers Ltd', 'First published in 1971, The Exorcist became a literary phenomenon and inspired one of the most shocking films ever made. This edition, polished and expanded by the author, includes new dialogue, a new character and a chilling new extended scene, provides an unforgettable reading experience that has lost none of its power to shock and continues to thrill and terrify new readers.', 12, 2, '2018-05-18', '2011-10-13', 'images/14.jpg', 'The terror begins unobtrusively. Noises in the attic. In the child\'s room, an odd smell, the displacement of furniture, an icy chill. At first, easy explanations are offered. Then frightening changes begin to appear in eleven-year-old Regan. Medical tests fail to shed any light on her symptoms, but it is as if a different personality has invaded her body.\r\n\r\nFather Damien Karras, a Jesuit priest, is called in. Is it possible that a demonic presence has possessed the child? Exorcism seems to be the only answer...', 0),
(15, '9780141191447', 'The Haunting of Hill House', 'Horror', 'Shirley Jackson', 'Penguin Books Ltd', 'The best-known of Shirley Jackson\'s novels, and the inspiration for writers such as Neil Gaiman and Stephen King, The Haunting of Hill House is a chilling story of the power of fear.\r\n\r\n\'Shirley Jackson\'s stories are among the most terrifying ever written\' Donna Tartt, author of The Goldfinch and The Secret History', 19, 4, '2018-05-18', '2009-01-10', 'images/15.jpg', 'Four seekers have arrived at the rambling old pile known as Hill House: Dr. Montague, an occult scholar looking for solid evidence of psychic phenomena; Theodora, his lovely assistant; Luke, the future inheritor of the estate; and Eleanor, a friendless, fragile young woman with a dark past. As they begin to cope with horrifying occurrences beyond their control or understanding, they cannot possibly know what lies ahead. For Hill House is gathering its powers - and soon it will choose one of them to make its own.', 0),
(16, '9780765357151', 'I Am Legend', 'Horror', 'Richard Matheson', 'Doherty Tom Associates U.S', 'In many ways this novel has been seen as the catalyst that re-invigorated the tired and dying genre that was horror of the 1950\'s, re-engineering a well known horror subject and yet written in a mainstream almost literary voice. It is widely regarded as being a major influence of the zombie genre and popularized the concept of a worldwide disease apocalypse. ', 7, 3, '2018-05-18', '2008-01-15', 'images/16.jpg', 'Robert Neville may well be the last living man on Earth . . . but he is not alone. \r\n\r\nAn incurable plague has mutated every other man, woman, and child into bloodthirsty, nocturnal creatures who are determined to destroy him. \r\n\r\nBy day, he is a hunter, stalking the infected monstrosities through the abandoned ruins of civilization. By night, he barricades himself in his home and prays for dawn.... ', 0),
(17, '9780963339744', 'The Girl Next Door', 'Horror', 'Jack Ketchum', 'Overlook Connection Press US', ' \"The Girl Next Door is alive.... in a way most works of poplular fiction never attain; it does not just promise terror but actually delievers it. But it\'s a page-turner, all right; no doubt about that.\" - Stephen King ', 38, 5, '2018-05-18', '2002-07-01', 'images/17.jpg', 'A teenage girl is held captive and brutally tortured by neighborhood children. Based on a true story, this shocking novel reveals the depravity of which we are all capable. \r\n\r\nThis novel contains graphic content and is recommended for regular readers of horror novels. ', 0),
(18, '9780575084353', 'Exquisite Corpse', 'Horror', 'Poppy Z. Brite', 'Orion Publishing Co', 'A terrifying novel of love and slaughter set in London and New Orleans. \r\nMoving from the grimy streets of London\'s Piccadilly Circus to the decadences of New Orleans\' French Quarter, Poppy Z. Brite dissects the landscape of torture and invites us into the mind of a serial killer in this riveting, unforgettable masterpiece of horror. ', 9, 8, '2018-05-18', '2008-08-21', 'images/18.jpg', 'To serial killer Andrew Compton, murder is an art, the most intimate art. After feigning his own death to escape from a life sentence in prison, he makes his way to America with the intention of bringing his art to new heights. Tortured by his own perverse desires, he inadvertently joins forces with Jay, a dissolute playboy. They set their sights on a young Vietnamese-American runaway, who they deem to be the perfect victim. ', 0),
(19, '9781444708134', 'Pet Sematary', 'Horror', 'Stephen King', 'Hodder & Stoughton General Division', 'A perennial classic from Stephen King - timeless and topical.\r\nA sad place maybe, but safe. Surely a safe place. Not a place to seep into your dreams, to wake you, sweating with fear and foreboding.', 11, 4, '2018-05-18', '2012-01-02', 'images/19.jpg', 'Rambling, old, unsmart and comfortable. A place where the family could settle; the children grow and play and explore. The rolling hills and meadows of Maine seemed a world away from the fume-choked dangers of Chicago.\r\n\r\nOnly the occasional big truck out on the two-lane highway, grinding up through the gears, hammering down the long gradients, growled out an intrusive threat.\r\n\r\nBut behind the house and far away from the road: that was safe. Just a carefully cleared path up into the woods where generations of local children have processed with the solemn innocence of the young, taking with them their dear departed pets for burial.', 0),
(20, '9780812979787', 'Night Film', 'Horror', 'Marisha Pessl', 'Random House Trade', 'NEW YORK TIMES BESTSELLER NAMED ONE OF THE BEST BOOKS OF THE YEAR BY\r\nNPR - Cosmopolitan - Kirkus Reviews - BookPage A page-turning thriller for readers of Stephen King, Gillian Flynn, and Stieg Larsson', 22, 2, '2018-05-18', '2014-12-11', 'images/20.jpg', 'In the Internet Age itâ€™s pretty easy to fall down a rabbit hole of pop culture obsession, and there are still dark areas of culture that havenâ€™t had a wiki created around them. Pesslâ€™s story about a mysterious underground filmmaker whose movies may or may not contain hints of dark power and horrific events and the journalist who becomes obsessed with him asks the reader how you can be certain thereâ€™s a clear line between fact and fiction, then, once that wedge of doubt is established, presents a terrifying fiction to fill that space.', 0),
(21, '9780143039693', 'Noli Me Tangere', 'History', 'Jose Rizal', 'Penguin Books Ltd', 'Noli Me Tangere is Latin for \"touch me not, \" an allusion to the Gospel of St. John where Jesus says to Mary Magdelene: \"Touch me not, for I am not yet ascended to my Father.\"\r\nThe popularity of this novel is grounded in its reflection of the turbulent times in which it was written. Its influence on Filipino political thinking, as well as on contemporary fiction, drama, opera, dance, and film, has been and continues to be enormous. The vivid characters and the harsh situations depicted still ring true today. ', 16, 5, '2018-05-23', '2006-12-07', 'images/21.jpg', 'In more than a century since its appearance, Jose Rizal\'s Noli Me Tangere has become widely known as the great novel of the Philippines. A passionate love story set against the ugly political backdrop of repression, torture, and murder, \"The Noli,\" as it is called in the Philippines, was the first major artistic manifestation of Asian resistance to European colonialism, and Rizal became a guiding conscience-and martyr-for the revolution that would subsequently rise up in the Spanish province. ', 0),
(22, '9780143106395', 'El Filibusterismo', 'History', 'Jose Rizal', 'Penguin Books Ltd', 'Jose Rizal was one of the leading champions of Filipino nationalism and independence. His masterpiece, \"Noli Me Tangere\", is widely considered to be the foundational novel of the Philippines. In this riveting continuation, which picks up the story thirteen years later, Rizal departs from the Noli\'s themes of innocent love and martyrdom to present a gripping tale of obsession and revenge. Clearly demonstrating Rizal\'s growth as a writer, and influenced by his exposure to international events, \"El Filibusterismo\" is a thrilling and suspenseful account of Filipino resistance to colonial rule that still resonates today. ', 17, 5, '2018-05-23', '2011-09-01', 'images/22.jpg', 'El Filibusterismo (\"\"The Subversive\"\") is the second novel by Jose Rizal (1861-1896), national hero of the Philippines. Characters from the \"\"Noli\"\" (Basilio, Dona Victorina, Padre Salvi) return while new ones are introduced: Simoun, the transformed Ibarra; Cabesang Tales and his struggle for justice; the nationalist student Isagani; the Indio priest Padre Florentino. Through them the colonial milieu is expanded - its officialdom, education, legal system, power plays, social patterns - and seen anew as context for conflict and insight. ', 0),
(23, '9789718958001', 'The Philippines: A Past Revisited Vol 1', 'History', 'Renato Constantino', 'Renato Constantino', 'This book is Constantino\'s attempt at a major breakthrough in Philippine historiography: he looks at the oppression of the Filipino masses from earliest time to 1941 and the struggle of men like himself to crack through the stereotypes hitherto propagated by Spaniards and Americans about the Filipinos.', 21, 4, '2018-05-23', '1975-01-01', 'images/23.jpg', 'n this book the traditional elements of historical writing are included but are critically examined against the background of changes in production relations and class structure and in the role of the Filipino people in the making of their own history.', 0),
(24, '9789712715457', 'A Question of Heroes', 'History', 'Nick Joaquin', 'Anvil', '', 75, 3, '2018-05-23', '2004-01-01', 'images/24.jpg', 'Through his critical essays on ten key figures in Philippine history, Nick Joaquin provides a fresh point of view on Philippine heroes and their role in the Philippine revolutionary tradition.', 0),
(25, '9789715083027', '101 Filipino Icons', 'History', 'Virgilio S. Almario', 'Adarna House', '', 30, 6, '2018-05-23', '2007-05-01', 'images/25.jpg', 'This book in color is a comprehensive survey of people, places, things and events that make Filipinos unique, 101 historical and cultural icons that all Filipinos should know. Each featured icon includes photographs, illustrations, information, trivia and quotes.', 0),
(26, '9789711901301', 'Dekada \'70', 'History', 'Lualhati Bautista', 'Cacho Publishing House', '', 30, 7, '2018-05-23', '1983-01-01', 'images/26.jpg', '\" Written even before the assassination of Nonoy Aquino, the novel surprises and delights wth ts bellicose and defiant pro-people stance in these days of between-the-lines journalism, self-censorship and multi-million peso libel suits. Where other writers would balk and simply hint by using vague metaphors and parallel cases, Bautista, in a work of supposed fiction, names names, cites actual atrocities and points an unerring finger where the blame lies...Veritas, Sept 26, 1984).\"', 0),
(27, '9780345328168', 'In Our Image: America\'s Empire in the Philippines', 'History', 'Stanley Karnow', 'Ballantine Books', 'â€œA brilliant, coherent social and political overview spanning three turbulent centuries.â€â€”San Francisco Chronicle', 21, 7, '2018-05-23', '1990-03-03', 'images/27.jpg', 'Stanley Karnow won the Pulitzer Prize for this account of Americaâ€™s imperial experience in the Philippines. In a swiftly paced, brilliantly vivid narrative, Karnow focuses on the relationship that has existed between the two nations since the United States acquired the country from Spain in 1898, examining how we have sought to remake the Philippines â€œin our image,â€ an experiment marked from the outset by blundering, ignorance, and mutual misunderstanding.', 0),
(28, '9789712709203', 'Rizal: Without the Overcoat', 'History', 'Ambeth R. Ocampo', 'Anvil Publishing', '\"Through writing about history, Ocampo writes on Rizal as if he happened yesterday. In the clean, cool style of a good journalist...Ocampo is one historian who has never known to impose dogmas and definitive treatises. Reading Ocampo\'s history is like sitting down with a friend who shares what he has learned. But what he does best is to share the certainty of his doubts. Which probably makes him less of a historian. But then history is too serious to be left to historians.\" ', 17, 5, '2018-05-23', '2003-01-01', 'images/28.jpg', 'A collection of articles from his \"Looking Back\" column, which was published in the Philippine Daily Globe and the Philippine Daily Inquirer.', 0),
(29, '9780842381390', 'In The Presence of My Enemies', 'History', 'Gracia Burnham', 'Tyndale Momentum', '', 14, 6, '2018-05-23', '2010-01-01', 'images/29.jpg', 'In the Presence of My Enemies, the gripping true story of American missionaries Martin and Gracia Burnhamâ€™s year as hostages in the Philippine jungle, was a New York Times best seller and has sold nearly 350,000 copies. Now releasing in trade softcover for the first time, this updated edition has a new look and contains never-before-published information on the capture and trial of the Burnhamsâ€™ captors; Graciaâ€™s secret return trip to the Philippines; and updates on recent events in Graciaâ€™s life, ministry, and family.', 0),
(30, '9786219544313', 'MARCOS MARTIAL LAW : NEVER AGAIN', 'History', 'Raissa Robles', 'FILIPINOS FOR A BETTER PHILIPPINES INC', '', 140, 1, '2018-05-23', '2016-01-01', 'images/30.jpg', 'IN SEPTEMBER 1972 FERDINAN MARCOS DECLARED MARTIAL LAW, PLUNGING THE PHILIPPINES INTO 14 YEARS OF A BRUTAL DICTATORSHIP THAT ONLY ENDED WHEN HE WAS CHASED OUT OF THE COUNTRY. ** TH HALLMARK OF HIS DICTATORSHIP WAS REPRESSION: THE SYSTEMATIC US OF TERROR, TORTURE AND MURDER. THOUSANDS WERE KILLED, TENS OF THOUSANDS MORE SUFFERED TORMENTS IN \"TACTICAL INTERROGATION\" SESSIONS CONDUCTED BY THE MILITARY, PARTICULARLY THE PHILIPPINE CONSTABULARY. ** IN THIS BRIEF ILLUSTRATED HISTORY, JOURNALIST AND BLOGGER RAISSA ROBLES RECOUNTS MARTIAL LAW\'S GRISLY RECORD OF HUMAN RIGHTS VIOLATIONS, CLEARLY ESTABLISHING THAT TORTURE WAS A DELIBERATE OLICY OF DICTATOR MARCOS. SHE CONTEXTS THIS AGAINST A BACKDROP OF HISTORICAL EVENTS AND EXPLAINS WHY AND HOW MARCOS GRABBED POWER UNDER THE GUISE OF FIGHTING A COMMUNIST THREAT. ** PUBLISHED ON THE 30TH ANNIVERSARY OF THE PEOPLE POWER UPRISING THAT OVERTHREW MARCO, THE BOOK WAS EDITED BY AWARD-WINNING JOURNALIST AND FOREIGN CORRESPONDENT ALAN ROBLES. ** USING BOOKS, DOCUMENTS AND OFFICIAL RECORDS, THE AUTHOR TRACES THE COURSE OF THE NEW SOCIETY, IDENTIFIES ITS KEY PLAYERS AND SHOWS HOW MARCOS USED MILITARY RULE TO KEEP HIMSELF IN POWER AND PERPETUATE A REGIME FOCUSED ON PLUNDERING THE ECONOMY. SHE RECONSTRUCTS MARCOS\' POLICE STATE INFRASTRUCTURE--COMPLETE WITH SPECIALLY BUILT DENTENTION CAMPS--AND ITS TECHNIQUES OF TORTURE. ROBLES INTERVIEWED SOURCES RANGING FROM TWO PHILIPPINE PRESIDENTS TO GENERALS, COLONELS AND TORTURE SURVIVORS. ** MARTIAL LAW\'S ATROCITIES LEFT A NATIONAL TRAUMA THAT HASN\'T HEALED. THE PERPETRATORS HAVE NOT ONLY GONE UNPUNISHED -- THEY HAVEN\'T EVEN ADMITTED TO COMMITTING TORTURE. SURVIVOR, PHYSICALLY AND PSYCHOLOGICALLY SCARRED, HAVE BEEN LEFT TO FEND FOR THEMSELVES. REMEMBRANCE OF THE HORRORS. THESE ARE NOW IN DANGER OF BEING FORGOTTEN, THANKS IN PART TO A CONCERTED EFFORT BY MARCOSES AND THEIR CRONIES TO ERASE THE PAST.', 0),
(31, '9780141184944', 'Silent Spring', 'Science', 'Rachel Carson', 'Penguin Books Ltd', 'Now recognized as one of the most influential books of the twentieth century, Silent Spring exposed the destruction of wildlife through the widespread use of pesticides. Despite condemnation in the press and heavy-handed attempts by the chemical industry to ban the book, Rachel Carson succeeded in creating a new public awareness of the environment which led to changes in government and inspired the ecological movement. It is thanks to this book, and the help of many environmentalists, that harmful pesticides such as DDT were banned from use in the US and countries around the world.', 11, 2, '2018-05-23', '2000-09-28', 'images/31.jpg', 'Rachel Carson\'s Silent Spring alerted a large audience to the environmental and human dangers of indiscriminate use of pesticides, spurring revolutionary changes in the laws affecting our air, land, and water. This Penguin Modern Classics edition includes an introduction by Lord Shackleton, a preface by World Wildlife Fund founder Julian Huxley, and an afterword by Carson\'s biographer Linda Lear.', 0),
(32, '9780465023820', 'The Feynman Lectures on Physics', 'Science', 'Matthew Sands, Richard P. Feynman', 'INGRAM PUBLISHER SERVICES US', '\"The whole thing was basically an experiment,\" Richard Feynman said late in his career, looking back on the origins of his lectures. The experiment turned out to be hugely successful, spawning a book that has remained a definitive introduction to physics for decades.', 164, 1, '2018-05-23', '2015-07-13', 'images/32.jpg', 'Ranging from the most basic principles of Newtonian physics through such formidable theories as general relativity and quantum mechanics, Feynman\'s lectures stand as a monument of clear exposition and deep insight. Now, we are reintroducing the printed books to the trade, fully corrected, for the first time ever, and in collaboration with Caltech. Timeless and collectible, the lectures are essential reading, not just for students of physics but for anyone seeking an introduction to the field from the inimitable Feynman. ', 0),
(33, '9780753828434', 'The Double Helix', 'Science', 'James Watson', 'Orion Publishing Co', '\'It is a strange model and embodies several unusual features. However, since DNA is an unusual substance, we are not hesitant in being bold\' \r\nBy elucidating the structure of DNA, the molecule underlying all life, Francis Crick and James Watson revolutionised biochemistry. At the time, Watson was only 24. His uncompromisingly honest account of those heady days lifts the lid on the real world of great scientists, with their very human faults and foibles, their petty rivalries and driving ambition. Above all, he captures the extraordinary excitement of their desperate efforts to beat their rivals at King\'s College to the solution to one of the great enigmas of the life sciences. ', 10, 3, '2018-05-23', '2010-11-11', 'images/33.jpg', 'The story of the most significant biological breakthrough of the century - the discovery of the structure of DNA. \r\n', 0),
(34, '9781591026679', 'The Cosmic Connection', 'Science', 'Jeff Kanipe', 'Prometheus Books', '', 33, 9, '2018-05-23', '2009-01-09', 'images/34.jpg', 'In this sweeping tour of the cosmos and our place within it, acclaimed science writer Jeff Kanipe shows the many ways we are connected to the vast universe we inhabit. Long before our apelike ancestors dropped from the trees and began playing with fire, even before the Sun emerged from its chrysalis of dust and irradiated its brood of planets, numberless and nameless astronomical events affected Earth and its emerging life-forms. Our chemical makeup--from the iron in our blood to the calcium in our bones--derives from stars that lived and died hundreds of millions of years ago. Comets have showered organic molecules into our oceans, and asteroid impacts have wiped out predominant species that lived before.\r\nTracing the whole natural history of how events in the near and far universe have influenced life on Earth today, and how they might influence life in the future, Kanipe, with unparalleled eloquence, explores a host of intriguing questions: - How the Earth\'s orbit and inclination have triggered past ice ages\r\n- The role ancient supernovae may have played in mass extinctions and genetic changes\r\n- How a slight but persistent dip in solar output contributed to a multicentury cooling event called the \"Little Ice Age\" \r\n- How ancient asteroid impacts pressed Earth\'s evolutionary reset button and how astronomers are striving to make sure that it won\'t happen again\r\n- The widespread effects that our Sun\'s changing galactic environment has on life and climate Kanipe also reflects upon the possible societal effects of alien contact, a type of cosmic intervention that some astronomers believe could happen within the next few decades. His elegant, jargon-free descriptions of the truly \"big-picture view\" of life on Earth will fascinate and inform everyone who has an interest in astronomy, the evolution of our planet, and the future of humankind.', 0),
(35, '9780198788607', 'The Selfish Gene', 'Science', 'Richard Dawkins', 'Oxford University Press', 'This 40th anniversary edition includes a new epilogue from the author discussing the continuing relevance of these ideas in evolutionary biology today, as well as the original prefaces and foreword, and extracts from early reviews. Oxford Landmark Science books are \'must-read\' classics of modern science writing which have crystallized big ideas, and shaped the way we think.', 14, 2, '2018-05-23', '2018-06-01', 'images/35.jpg', 'The million copy international bestseller, critically acclaimed and translated into over 25 languages. As influential today as when it was first published, The Selfish Gene has become a classic exposition of evolutionary thought. Professor Dawkins articulates a gene\'s eye view of evolution - a view giving centre stage to these persistent units of information, and in which organisms can be seen as vehicles for their replication. This imaginative, powerful, and stylistically brilliant work not only brought the insights of Neo-Darwinism to a wide audience, but galvanized the biology community, generating much debate and stimulating whole new areas of research. Forty years later, its insights remain as relevant today as on the day it was published. ', 0),
(36, '9780198784883', 'Gaia : A New Look at Life on Earth', 'Science', 'James Lovelock', 'Oxford University Press', ' In a new Preface to this edition, he outlines his view of the present state of the debate. Oxford Landmark Science books are \'must-read\' classics of modern science writing which have crystallized big ideas, and shaped the way we think. ', 9, 4, '2018-05-23', '2016-07-01', 'images/36.jpg', 'In this classic work that continues to inspire many readers, Jim Lovelock puts forward his idea that the Earth functions as a single organism. Written for non-scientists, Gaia is a journey through time and space in search of evidence in support of a radically different model of our planet. In contrast to conventional belief that life is passive in the face of threats to its existence, the book explores the hypothesis that the Earth\'s living matter influences air, ocean, and rock to form a complex, self-regulating system that has the capacity to keep the Earth a fit place for life. Since Gaia was first published, Jim Lovelock\'s hypothesis has become a hotly debated topic in scientific circles.', 0),
(37, '9780465024377', 'The First Three Minutes', 'Science', 'Steven Weinberg', 'INGRAM PUBLISHER SERVICES US', '', 14, 1, '2018-05-23', '1993-08-18', 'images/37.jpg', 'This classic of contemporary science writing by a Nobel Prize-winning physicist explains to general readers what happened when the universe began, and how we know. ', 0),
(38, '9780674016385', 'On Human Nature', 'Science', 'Edward O. Wilson', 'HARVARD UNIVERSITY PRESS', 'View a collection of videos on Professor Wilson entitled \"On the Relation of Science and the Humanities\" ', 30, 5, '2018-05-23', '2004-11-22', 'images/38.jpg', 'In his new preface E. O. Wilson reflects on how he came to write this book: how The Insect Societies led him to write Sociobiology, and how the political and religious uproar that engulfed that book persuaded him to write another book that would better explain the relevance of biology to the understanding of human behavior. ', 0),
(39, '9780753811412', 'Gorillas in the Mist', 'Science', 'Dian Fossey', 'Orion Publishing Co', 'Dian Fossey\'s classic account of four gorilla families; the basis for the major movie starring Sigourney Weaver ', 11, 6, '2018-05-23', '2001-05-01', 'images/39.jpg', 'For thirteen years Dian Fossey lived and worked with Uncle Bert, Flossie, Beethoven, Pantsy and Digit in the remote rain forests of the volcanic Virunga Mountains in Africa, establishing an unprecedented relationship with these shy and affectionate beasts. \r\n\r\nIn her base camp, 10,000 feet above sea-level, she struggled daily with rain, loneliness and the ever-constant threat of poachers who slaughtered her beloved gorillas with horrifying ferocity. African adventure, personal quest and scientific study, Gorillas in the Mist is a unique and intimate glimpse into a vanishing world and a vanishing species. ', 0),
(40, '9780198707653', 'Origins : The Scientific Story of Creation', 'Science', 'Jim Baggott', 'Oxford University Press', '', 22, 10, '2018-05-23', '2017-11-09', 'images/40.jpg', 'What is life? Where do we come from and how did we evolve? What is the universe and how was it formed? What is the nature of the material world? How does it work? How and why do we think? What does it mean to be human? How do we know? There are many different versions of our creation story. This book tells the version according to modern science. It is a unique account, starting at the Big Bang and travelling right up to the emergence of humans as conscious intelligent beings, 13.8 billion years later. Chapter by chapter, it sets out the current state of scientific knowledge: the origins of space and time; energy, mass, and light; galaxies, stars, and our sun; the habitable earth, and complex life itself. Drawing together the physical and biological sciences, Baggott recounts what we currently know of our history, highlighting the questions science has yet to answer. ', 0),
(41, '9780099560432', 'Ready Player One', 'Fiction', 'Ernest Cline', 'Cornerstone', '`Wildly original and stuffed with irresistible nostalgia, Ready Player One is a spectacularly genre-busting, ambitious, and charming debut\' Independent\r\n\r\n`Part intergalactic scavenger hunt, part romance, and all heart\' CNN \r\n\r\n`Ernest Cline\'s novel deserves to be a modern classic\' SciFiNow\r\n\r\n`Gorgeously geeky, superbly entertaining, this really is a spectacularly successful debut\' Daily Mail\r\n\r\n', 10, 2, '2018-05-23', '2012-04-05', 'images/41.jpg', 'Like most of humanity, Wade Watts escapes this depressing reality by spending his waking hours jacked into the OASIS, a sprawling virtual utopia where you can be anything you want to be, where you can live and play and fall in love on any of ten thousand planets. And like most of humanity, Wade is obsessed by the ultimate lottery ticket that lies concealed within this alternate reality: OASIS founder James Halliday, who dies with no heir, has promised that control of the OASIS - and his massive fortune - will go to the person who can solve the riddles he has left scattered throughout his creation. \r\n\r\nFor years, millions have struggled fruitlessly to attain this prize, knowing only that the riddles are based in the culture of the late twentieth century. And then Wade stumbles onto the key to the first puzzle.\r\n\r\nSuddenly, he finds himself pitted against thousands of competitors in a desperate race to claim the ultimate prize, a chase that soon takes on terrifying real-world dimensions - and that will leave both Wade and his world profoundly changed.', 0),
(42, '9780099511663', 'The Handmaid\'s Tale', 'Fiction', 'Margaret Atwood', 'Vintage Publishing', 'Brilliantly conceived and executed, this powerful evocation of twenty-first century America explores a world in which oppression of women, and repression of the truth, have become justified. ', 10, 7, '2018-05-23', '2011-06-29', 'images/42.jpg', 'Offred is a Handmaid in the Republic of Gilead. She has only one function: to breed. If she deviates, she will, like dissenters, be hanged at the wall or sent out to die slowly of radiation sickness. But even a repressive state cannot obliterate desire - neither Offred\'s nor that of the two men on which her future hangs. ', 0),
(43, '9780812550702', '     Ender\'s Game', 'Fiction', 'Ender Wiggin Saga', 'St Martin\'s Press', 'Ender\'s Game is the winner of the 1985 Nebula Award for Best Novel and the 1986 Hugo Award for Best Novel.', 7, 3, '2018-05-23', '1998-11-30', 'images/43.jpg', 'In order to develop a secure defense against a hostile alien race\'s next attack, government agencies breed child geniuses and train them as soldiers. A brilliant young boy, Andrew \"Ender\" Wiggin lives with his kind but distant parents, his sadistic brother Peter, and the person he loves more than anyone else, his sister Valentine. Peter and Valentine were candidates for the soldier-training program but didn\'t make the cut--young Ender is the Wiggin drafted to the orbiting Battle School for rigorous military training.\r\n\r\nEnder\'s skills make him a leader in school and respected in the Battle Room, where children play at mock battles in zero gravity. Yet growing up in an artificial community of young soldiers Ender suffers greatly from isolation, rivalry from his peers, pressure from the adult teachers, and an unsettling fear of the alien invaders. His psychological battles include loneliness, fear that he is becoming like the cruel brother he remembers, and fanning the flames of devotion to his beloved sister. \r\n', 0),
(44, '9780340960196', 'Dune', 'Fiction', 'Frank Herbert', 'Hodder & Stoughton General Division', 'Before The Matrix, before Star Wars, before Ender\'s Game and Neuromancer, there was Dune: winner of the prestigious Hugo and Nebula awards, and widely considered one of the greatest science fiction novels ever written.', 12, 6, '2018-05-23', '2015-07-31', 'images/44.jpg', 'Melange, or \'spice\', is the most valuable - and rarest - element in the universe; a drug that does everything from increasing a person\'s life-span to making intersteller travel possible. And it can only be found on a single planet: the inhospitable desert world Arrakis.\r\n\r\nWhoever controls Arrakis controls the spice. And whoever controls the spice controls the universe.\r\n\r\nWhen the Emperor transfers stewardship of Arrakis from the noble House Harkonnen to House Atreides, the Harkonnens fight back, murdering Duke Leto Atreides. Paul, his son, and Lady Jessica, his concubine, flee into the desert. On the point of death, they are rescued by a band for Fremen, the native people of Arrakis, who control Arrakis\' second great resource: the giant worms that burrow beneath the burning desert sands.\r\n\r\nIn order to avenge his father and retake Arrakis from the Harkonnens, Paul must earn the trust of the Fremen and lead a tiny army against the innumerable forces aligned against them.\r\n\r\nAnd his journey will change the universe.', 0),
(45, '9780141036144', 'Nineteen Eighty-Four', 'Fiction', 'George Orwell', 'Penguin Books Ltd', 'Renowned urban artist Shepard Fairey\'s new look for Orwell\'s classic dystopian tale\r\n\r\nOne of Britain\'s most popular novels, George Orwell\'s Nineteen Eighty-Four is set in a society terrorised by a totalitarian ideology propagated by The Party. \r\n', 8, 3, '2018-05-23', '2008-11-01', 'images/45.jpg', 'Winston Smith works for the Ministry of Truth in London, chief city of Airstrip One. Big Brother stares out from every poster, the Thought Police uncover every act of betrayal. When Winston finds love with Julia, he discovers that life does not have to be dull and deadening, and awakens to new possibilities. Despite the police helicopters that hover and circle overhead, Winston and Julia begin to question the Party; they are drawn towards conspiracy. Yet Big Brother will not tolerate dissent - even in the mind. For those with original thoughts they invented Room 101. . . ', 0),
(46, '9781451690316', 'Fahrenheit 451', 'Fiction', 'Ray Bradbury', 'SIMON & SCHUSTER', '', 6, 5, '2018-05-23', '2012-05-23', 'images/46.jpg', 'Guy Montag is a fireman. In his world, where television rules and literature is on the brink of extinction, firemen start fires rather than put them out. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television â€œfamily.â€ But then he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didnâ€™t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television. When Mildred attempts suicide and Clarisse suddenly disappears, Montag begins to question everything he has ever known. He starts hiding books in his home, and when his pilfering is discovered, the fireman has to run for his life. ', 0),
(47, '9780751554144', 'I See You', 'Fiction', 'Clare Mackintosh', 'Little, Brown Book Group', '\'I See You is both a compelling portrayal of modern family life and a superbly twisty thriller that keeps you guessing until the very last page. An edge of the seat read\' Kate Hamer, author of The Girl in the Red Coat\r\n\r\n\'Anyone who\'s ever looked over their shoulder when they heard footsteps behind them, or quickened their pace in a deserted underpass, will shudder with recognition at Clare Mackintosh\'s deliciously creepy tale of urban paranoia\' Ruth Ware, author of In a Dark, Dark Wood\r\n\r\n\'I was gripped from the very first page. Creepy and compelling with a twist I didn\'t see coming. I loved it\' Claire Douglas, author of The Sisters\r\n\r\n\'As creepy as they come . . . We raced through this deeply unsettling thriller in two days . . . and looked over our shoulder the whole time\' Heat\r\n\r\n\'Another edge-of-your-seat thriller . . . a terrifyingly plausible plot and gasp-inducing ending\' Good Housekeeping\r\n', 6, 5, '2018-05-23', '2017-04-20', 'images/47.jpg', 'When Zoe Walker sees her photo in the classifieds section of a London newspaper, she is determined to find out why it\'s there. There\'s no explanation: just a grainy image, a website address and a phone number. She takes it home to her family, who are convinced it\'s just someone who looks like Zoe. But the next day the advert shows a photo of a different woman, and another the day after that.\r\n\r\nIs it a mistake? A coincidence? Or is someone keeping track of every move they make . . .', 0),
(48, '9781786495259', 'Call Me By Your Name', 'Fiction', 'Andre Aciman', 'ATLANTIC BOOKS', 'ow a Major Motion Picture from Director Luca Guadagnino, Starring Armie Hammer and Timothee Chalamet, and Written by Three-Time OscarT Nominee James Ivory\r\n\r\nNominated for Four OscarsT\r\n\r\nA New York Times Bestseller\r\nA USA Today Bestseller \r\nA Los Angeles Times Bestseller\r\nA Vulture Book Club Pick\r\nAn Instant Classic and One of the Great Love Stories of Our Time\r\n', 10, 8, '2018-05-23', '2018-04-03', 'images/48.jpg', '\r\n   \r\nCall Me By Your Name\r\n 4.3 (57,911 ratings by Goodreads)\r\nPaperback English\r\nBy (author)  Andre Aciman\r\nShare    \r\nAlso available in\r\nHardback US$23.77\r\nCD-Audio US$30.08\r\nNow a Major Motion Picture from Director Luca Guadagnino, Starring Armie Hammer and Timothee Chalamet, and Written by Three-Time OscarT Nominee James Ivory\r\n\r\nNominated for Four OscarsT\r\n\r\nA New York Times Bestseller\r\nA USA Today Bestseller \r\nA Los Angeles Times Bestseller\r\nA Vulture Book Club Pick\r\nAn Instant Classic and One of the Great Love Stories of Our Time\r\n\r\nAndre Aciman\'s Call Me by Your Name is the story of a sudden and powerful romance that blossoms between an adolescent boy and a summer guest at his parents\' cliffside mansion on the Italian Riviera. Each is unprepared for the consequences of their attraction, when, during the restless summer weeks, unrelenting currents of obsession, fascination, and desire intensify their passion and test the charged ground between them. Recklessly, the two verge toward the one thing both fear they may never truly find again: total intimacy. It is an instant classic and one of the great love stories of our time.', 0),
(49, '9780857524195', 'The Travelling Cat Chronicles', 'Fiction', 'Hiro Arikawa', 'Transworld Publishers Ltd', 'RECOMMENDED BY THOUSANDS OF INTERNATIONAL READERS - the tender feelgood story of a man\'s journey around Japan with a streetcat. Translated by Philip Gabriel, a translator of Murakami. \r\n\r\nINCLUDES SPECIALLY COMMISSIONED LINE-DRAWINGS\r\nA WATERSONES PAPERBACK OF THE YEAR 2017\r\n\r\n\'Anyone who has ever unashamedly loved an animal will read this book with gratitude, for its understanding of an emotion that ennobles us as human beings, whether we value it or not\' LYNNE TRUSS, Guardian', 10, 1, '2018-05-23', '2018-01-30', 'images/49.jpg', 'It\'s not the journey that counts, but who\'s at your side.\r\n\r\nNana is on a road trip, but he is not sure where he is going. All that matters is that he can sit beside his beloved owner Satoru in the front seat of his silver van. Satoru is keen to visit three old friends from his youth, though Nana doesn\'t know why and Satoru won\'t say. \r\n\r\nSet against the backdrop of Japan\'s changing seasons and narrated with a rare gentleness and humour, Nana\'s story explores the wonder and thrill of life\'s unexpected detours. It is about the value of friendship and solitude, and knowing when to give and when to take. TRAVELLING CAT has already demonstrated its power to move thousands of readers with a message of kindness and truth. It shows, above all, how acts of love, both great and small, can transform our lives.', 0),
(50, '9781509800452', 'Accidental Heroes', 'Fiction', 'Danielle Steel', 'Pan MacMillan', 'Danielle Steel combines intense action with stories of emotionally rich, intertwined lives. As the plane bears down on its destination of San Francisco, the futures of these strangers will be changed forever by a handful of accidental heroes.\r\n\r\nAccidental Heroes is a heart-stopping thriller about ordinary men and women who embark on a journey they will never forget.', 20, 4, '2018-05-23', '2018-04-05', 'images/50.jpg', 'On a beautiful May morning at New York\'s JFK Airport, a routine plane departs for San Francisco. Security agent Bernice Adams finds a postcard of the Golden Gate Bridge bearing an ambiguous message. Who left the postcard behind, which flight is that person on, and what exactly does the message mean? Her supervisor dismisses her concerns but she is compelled to contact Homeland Security.\r\n\r\nAs the flight takes off each of the passengers is looking forward to reaching San Francisco, whether it\'s for a family reunion, a wedding, or a new way of life. But as it emerges, there\'s someone on the flight planning something terrible and these strangers\' lives entwine as they come together to help to avert a tragedy at the eleventh hour.', 0);
INSERT INTO `book_details` (`B_ID`, `B_ISBN`, `B_TITLE`, `B_GENRE`, `B_AUTHOR`, `B_PUBLISHER`, `B_DESC`, `B_PRICE`, `B_QTY`, `B_REGISTERED`, `B_PUBLISHED`, `B_IMG`, `B_OTHER`, `RENT_COUNT`) VALUES
(51, '9780380810338', 'Feeling Good : The New Mood Therapy', 'Psych', 'David D. Burns', 'HarperCollins Publishers Inc', 'Burnâ€™s theories in â€œFeeling Goodâ€ have revolutionized the field of Psychology, which has solidified its place among the most significant self-help books ever published.', 9, 6, '2018-05-23', '2011-07-11', 'images/51.jpg', '\r\nThis book, published in 1980, is responsible for bringing Cognitive Behavioral Therapy to the forefront of psychoanalytic theory. Cognitive Behavioral Therapy is a treatment strategy for depression that involves conscious restructuring of harmful thought and behavior patterns under the care of a trained psychotherapist. Burnâ€™s best-seller is responsible for bringing this theory out of academia and to the average reader.\r\nOver the last 35 years, â€œFeeling Goodâ€ has become one of the most recommended books by psychologists to help depression patients understand their destructive thought patterns. It was one of the cornerstones in popularizing bibliotherapy, as research has shown depression patients who read â€œFeeling Goodâ€ as a supplement to regular check-ins with a mental health professional see sustained improvements in mood.\r\n', 0),
(52, '9780141043029', 'Outliers : The Story of Success', 'Psych', 'Malcolm Gladwell', 'Penguin Books Ltd', 'Just as he did in Blink, Gladwell overturns many of our conventional notions and creates an entirely new model for seeing the world. Brilliant and entertaining, this is a landmark work that will simultaneously delight and illuminate.', 9, 10, '2018-05-23', '2009-06-04', 'images/52.jpg', 'Why are people successful? For centuries, humankind has grappled with this question, searching for the secret to accomplishing great things. In this stunning new book, Malcolm Gladwell takes us on an invigorating intellectual journey to show us what makes an extreme overachiever.\r\n\r\nHe reveals that we pay far too much attention to what successful people are like, and too little attention to where successful people are from: their culture, their family, and their generation. Gladwell examines how the careers of Bill Gates and the performance of world-class football players are alike; what top fighter pilots and The Beatles have in common; why so many top lawyers are Jewish; why Asians are good at maths; and why it is correct to say that the mathematician who solved Fermat\'s Theorem is not a genius.', 0),
(53, '9781451639612', 'The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change', 'Psych', 'Dr Stephen R Covey', 'SIMON & SCHUSTER', 'This twenty-fifth anniversary edition of Stephen Covey\'s cherished classic commemorates the timeless wisdom of the 7 Habits. One of the most inspiring and impactful books ever written, The 7 Habits of Highly Effective People has captivated readers for 25 years. It has transformed the lives of Presidents and CEOs, educators and parents-- in short, millions of people of all ages and occupations. ', 16, 7, '2018-05-23', '2013-11-19', 'images/53.jpg', '', 0),
(54, '9780340978504', 'The Last Lecture', 'Psych', 'Randy Pausch', 'Hodder & Stoughton General Division', 'The phenomenal international bestseller - with over 8 million copies sold.\r\nWhat legacy would you choose to leave behind for your children?\r\nWhen Randy Pausch, a computer science professor at Carnegie Mellon, was asked to give \'a last lecture\' lecture, he didn\'t have to imagine it as his last, since he had recently been diagnosed with terminal pancreatic cancer. But the lecture he gave, \'Really Achieving Your Childhood Dreams\', wasn\'t about dying. It was about the importance of overcoming obstacles, of enabling the dreams of others, of seizing every moment (because time is all you have and you may find one day that you have less than you think). It was a summation of everything Randy had come to believe. It was about living.', 8, 1, '2018-05-23', '2010-06-24', 'images/54.jpg', 'A lot of professors give talks titled \'The Last Lecture\'. Professors are asked to consider their demise and to ruminate on what matters most to them: What wisdom would we impart to the world if we knew it was our last chance? If we had to vanish tomorrow, what would we want as our legacy?\r\n\r\nIn this book, Randy Pausch has combined the humour, inspiration, and intelligence that made his lecture such a phenomenon and given it an indelible form. It is a book that will be shared for generations to come.', 0),
(55, '9781400062751', 'Mindset: The New Psychology of Success', 'Psych', 'Caro S Dweck', 'Random House USA Inc', 'This is a book that can change your life, as its ideas have changed mine.\"--Robert J. Sternberg, co-author of Teaching for Wisdom, Intelligence, Creativity, and Success \"An essential read for parents, teachers [and] coaches . . . as well as for those who would like to increase their own feelings of success and fulfillment.\"--Library Journal (starred review) \"Everyone should read this book.\"--Chip Heath and Dan Heath, authors of Made to Stick \"One of the most influential books ever about motivation.\"--Po Bronson, author of NurtureShock \"If you manage people or are a parent (which is a form of managing people), drop everything and read Mindset.\"--Guy Kawasaki', 25, 3, '2018-05-23', '2006-03-15', 'images/55.jpg', ' In this brilliant book, she shows how success in school, work, sports, the arts, and almost every area of human endeavor can be dramatically influenced by how we think about our talents and abilities. People with a fixed mindset--those who believe that abilities are fixed--are less likely to flourish than those with a growth mindset--those who believe that abilities can be developed. Mindset reveals how great parents, teachers, managers, and athletes can put this idea to use to foster outstanding accomplishment. In this edition, Dweck offers new insights into her now famous and broadly embraced concept. She introduces a phenomenon she calls false growth mindset and guides people toward adopting a deeper, truer growth mindset. She also expands the mindset concept beyond the individual, applying it to the cultures of groups and organizations. With the right mindset, you can motivate those you lead, teach, and love--to transform their lives and your own. Praise for Mindset \"A good book is one whose advice you believe. A great book is one whose advice you follow.', 0),
(56, '9780762416844', 'The Purpose-Driven Life', 'Psych', 'Rick Warren', 'Running Press', '', 4, 2, '2018-05-23', '2014-02-13', 'images/56.jpg', 'Rick Warren, founding pastor of Saddleback Church in Lake Forest, California, one of America\'s largest and best-known churches, shows you how to lead a Purpose-Driven Life. This Miniature Edition (TM) will help you understand why you are alive and God\'s amazing plan for you- both here and now, and for eternity. ', 0),
(57, '9781841936161', 'The Prophet', 'Psych', 'Kahlil Gibran', 'Arcturus Publishing Ltd', '', 8, 6, '2018-05-23', '2010-06-01', 'images/57.jpg', 'First published in the 1920s, this book attempts to provide the reader with a guide to living. Gibran lets his protagonist, called simply the prophet, deliver homilies on a variety of topics central to daily life: love marriage and children, work and play, possessions, beauty, truth, joy and sorrow and death. ', 0),
(58, '9781591792383', 'Getting Unstuck', 'Psych', 'Pema Chodron', 'SOUNDS TRUE INC', 'Have you ever had an itch and not scratched it? In the Buddhist tradition, this points to a vast paradox: that by refraining from our urge to scratch, great peace and happiness is available.', 19, 2, '2018-05-23', '2005-01-01', 'images/58.jpg', 'On Getting Unstuck, Pema ChÃ¶drÃ¶n introduces a rare Tibetan teaching she received from her teacher, Dzigar Kontrul Rinpoche, and one that has become critical to her practice. Here, she unveils the mystery of an ineffable quality: a pre-emotional feeling that arises in us, brings us discomfort, and causes us to react by escaping the discomfort often with harmful habits.\r\n\r\nWith Getting Unstuck, she offers us a first look at both the itch and the scratch, which Tibetan Buddhists call shenpa. On this full-length recording, Pema ChÃ¶drÃ¶n, bestselling author and beloved American Buddhist nun, shows us how to recognize shenpa, catch it as it appears, and develop a playful, lively curiosity toward it. Join Pema ChÃ¶drÃ¶n to discover more about: \r\n\r\nCritical mind--how to recognize this fundamental shenpa, and approach yourself and others with a sense of humor and loving-kindnessWays to unravel the patterns of self-denigration, and develop the fundamental maitri--loving-kindness--toward yourselfHow to cultivate acceptance of your irritability, insecurities, and other simply human traitsRecognition, Refrain, Relaxing, and Resolve: the four R\'s of working with shenpa, and more\r\n\r\nAn urge comes up, we succumb to it, and it becomes stronger, teaches Pema ChÃ¶drÃ¶n. We reinforce our cravings, habits, and addictions by giving in to them repeatedly. On Getting Unstuck, ChÃ¶drÃ¶n guides us through this sticky feeling, exploring the moments when we get hooked, and offers us tools for learning to stay with our uneasiness, soften our hearts toward ourselves and others, and live a more peaceful life in the fullness of the present moment.', 0),
(59, '9780812981605', 'The Power of Habit : Why We Do What We Do in Life and Business', 'Psych', 'Charles Duhigg', 'Random House USA Inc', 'NEW YORK TIMES BESTSELLER - The perfect graduation gift, this instant classic explores how we can change our lives by changing our habits. \"With the days of pulling all-nighters and eating pizza at 2 a.m. (hopefully) behind your new grad, there\'s no time like the present to get into a good routine.\"--Real Simple NAMED ONE OF THE BEST BOOKS OF THE YEAR BY\r\nThe Wall Street Journal - Financial Times', 15, 9, '2018-05-23', '2014-07-01', 'images/59.jpg', 'Charles Duhigg takes us to the thrilling edge of scientific discoveries that explain why habits exist and how they can be changed. Distilling vast amounts of information into engrossing narratives that take us from the boardrooms of Procter & Gamble to the sidelines of the NFL to the front lines of the civil rights movement, Duhigg presents a whole new understanding of human nature and its potential. At its core, The Power of Habit contains an exhilarating argument: The key to exercising regularly, losing weight, being more productive, and achieving success is understanding how habits work. As Duhigg shows, by harnessing this new science, we can transform our businesses, our communities, and our lives.', 0),
(60, '9780340733509', 'The Power of Now', 'Psych', 'Eckhart Tolle', 'Hodder & Stoughton General Division', 'To make the journey into The Power of Now we will need to leave our analytical mind and its false created self, the ego, behind. Although the journey is challenging, Eckhart Tolle offers simple language and a question and answer format to show us how to silence our thoughts and create a liberated life.\r\n\r\nSurrender to the present moment, where problems do not exist. It is here we find our joy, are able to embrace our true selves and discover that we are already complete and perfect. If we are able to be fully present and take each step in the Now we will be opening ourselves to the transforming experience of The Power of Now. ', 10, 2, '2018-05-23', '2001-02-01', 'images/60.jpg', 'The bestselling self-help book of its generation - which has now sold over a million copies in the UK alone. Eckhart Tolle demonstrates how to live a healthier and happier life by living in the present moment. ', 0),
(61, '9780747568766', 'Just Kids', 'Entertainment', 'Patti Smith', 'Bloomsbury Publishing PLC', 'Just Kids begins as a love story and ends as an elegy. Beautifully written, this is a profound portrait of two young artists, often hungry, sated only by art and experience. And an unforgettable portrait of New York, her rich and poor, hustlers and hellions, those who made it and those whose memory lingers near.', 10, 4, '2018-05-23', '2010-12-01', 'images/61.jpg', 'In 1967, a chance meeting between two young people led to a romance and a lifelong friendship that would carry each to international success never dreamed of. The backdrop is Brooklyn, Chelsea Hotel, Max\'s Kansas City, Scribner\'s Bookstore, Coney Island, Warhol\'s Factory and the whole city resplendent. Among their friends, literary lights, musicians and artists such as Harry Smith, Bobby Neuwirth, Allen Ginsberg, Sandy Daley, Sam Shepherd, William Burroughs, etc. It was a heightened time politically and culturally; the art and music worlds exploding and colliding. In the midst of all this two kids made a pact to always care for one another. Scrappy, romantic, committed to making art, they prodded and provided each other with faith and confidence during the hungry years--the days of cous-cous and lettuce soup. ', 0),
(62, '9781407179858', 'Tom Gates: Biscuits, Bands and Very Big Plans', 'Entertainment', 'Liz Pichon', 'Scholastic', 'The bestselling fully-illustrated Tom Gates series is back with a\r\nnew book!', 14, 11, '2018-05-23', '2018-05-03', 'images/62.jpg', 'This book is VERY important because it contains BISCUITS, BANDS and\r\nall my (doodled) plans to make DogZombies the BEST band in the\r\nworld.\r\n\r\nMY VERY BIG PLAN:\r\n1. Write more songs about VERY important things like...\r\n... biscuits\r\n2. Make sure there\'s a good supply of SNACKS for our band practice\r\n\r\n3. Avoid Delia at ALL COSTS, she thinks I\'ve been SNOOPING in her\r\nroom. (I have.)\r\n4. DOODLE as much as possible, especially if Marcus is watching\r\n\r\nThe 14th book in this HILARIOUS series!', 0),
(63, '9780316056892', 'Bossypants', 'Entertainment', 'Tina Fey', 'Little, Brown & Company', '', 8, 3, '2018-05-23', '2013-01-29', 'images/63.jpg', 'Before Liz Lemon, before \"Weekend Update,\" before \"Sarah Palin,\" Tina Fey was just a young girl with a dream: a recurring stress dream that she was being chased through a local airport by her middle-school gym teacher. She also had a dream that one day she would be a comedian on TV. \r\nShe has seen both these dreams come true. \r\nAt last, Tina Fey\'s story can be told. From her youthful days as a vicious nerd to her tour of duty on Saturday Night Live; from her passionately halfhearted pursuit of physical beauty to her life as a mother eating things off the floor; from her one-sided college romance to her nearly fatal honeymoon -- from the beginning of this paragraph to this final sentence. \r\nTina Fey reveals all, and proves what we\'ve all suspected: you\'re no one until someone calls you bossy. ', 0),
(64, '9781742372389', 'The Happiest Refugee', 'Entertainment', 'Anh Do', 'Allen & Unwin', 'The Happiest Refugee tells the incredible, uplifting and inspiring life story of one of our favourite personalities. Tragedy, humour, heartache and unswerving determination - a big life with big dreams. Anh\'s story will move and amuse all who read it.', 21, 1, '2018-05-23', '2010-09-01', 'images/64.jpg', '\r\nAnh Do nearly didn\'t make it to Australia. His entire family came close to losing their lives on the sea as they escaped from war-torn Vietnam in an overcrowded boat. But nothing - not murderous pirates, nor the imminent threat of death by hunger, disease or dehydration as they drifted for days - could quench their desire to make a better life in a country where freedom existed.\r\n\r\nLife in Australia was hard, an endless succession of back-breaking work, crowded rooms, ruthless landlords and make-do everything. But there was a loving extended family, and always friends and play and something to laugh about for Anh, his brother Khoa and their sister Tram. Things got harder when their father left home when Anh was thirteen - they felt his loss very deeply and their mother struggled to support the family on her own. His mother\'s sacrifice was an inspiration to Anh and he worked hard during his teenage years to help her make ends meet, also managing to graduate high school and then university.\r\n', 0),
(65, '9781408708989', 'Fantastic Beasts and Where to Find Them', 'Entertainment', 'J.K Rowling', ' Little, Brown Book Group', 'Featuring a cast of remarkable characters, this is epic, adventure-packed storytelling at its very best. Whether an existing fan or new to the wizarding world, this is a perfect addition to any reader\'s bookshelf. ', 17, 5, '2018-05-23', '2016-11-19', 'images/65.jpg', 'When Magizoologist Newt Scamander arrives in New York, he intends his stay to be just a brief stopover. However, when his magical case is misplaced and some of Newt\'s fantastic beasts escape, it spells trouble for everyone...Fantastic Beasts and Where to Find Them marks the screenwriting debut of J.K. Rowling, author of the beloved and internationally bestselling Harry Potter books.', 0),
(66, '9780143036531', 'Amusing Ourselves to Death', 'Entertainment', 'Neil Postman', 'Penguin Putnam Inc', '', 13, 7, '2018-05-23', '2011-07-22', 'images/66.jpg', ' In this eloquent, persuasive book, Neil Postman alerts us to the real and present dangers of this state of affairs, and offers compelling suggestions as to how to withstand the media onslaught. Before we hand over politics, education, religion, and journalism to the show business demands of the television age, we must recognize the ways in which the media shape our lives and the ways we can, in turn, shape them to serve out highest goals. ', 0),
(67, '9781681883731', 'The Art & Making of the Greatest Showman', 'Entertainment', 'Signe Bergstrom', 'Weldon Owen, Incorporated', '', 38, 7, '2018-05-23', '2018-05-27', 'images/67.jpg', 'The Greatest Showman is a bold and original musical that celebrates the birth of show business and the sense of wonder we feel when dreams come to life. Inspired by the ambition and imagination of P.T. Barnum, The Greatest Showman tells the story of a visionary who rose from nothing to create a mesmerising spectacle that became a worldwide sensation.', 0),
(68, '9781627798341', 'Something Wonderful', 'Entertainment', 'Todd S. Purdum', 'Henry Holt & Company Inc', 'A revelatory portrait of the creative partnership that transformed musical theater and provided the soundtrack to the American Century', 32, 2, '2018-05-23', '2018-04-10', 'images/68.jpg', 'Todd S. Purdum\'s portrait of these two men, their creative process, and their groundbreaking innovations will captivate lovers of musical theater, lovers of the classic American songbook, and young lovers wherever they are. He shows that what Rodgers and Hammerstein wrought was truly something wonderful.', 0),
(69, '9780141978109', 'Into The Woods', 'Entertainment', 'John Yorke', 'Penguin Books Ltd', 'We all love stories. But why do we tell them? And why do all stories function in an eerily similar way? John Yorke, creator of the BBC Writers\' Academy, has brought a vast array of drama to British screens.', 12, 2, '2018-05-23', '2015-11-06', 'images/69.jpg', 'Here he takes us on a journey to the heart of storytelling, revealing that there truly is a unifying shape to narrative forms - one that echoes the fairytale journey into the woods and, like any great art, comes from deep within. From ancient myths to big-budget blockbusters, he gets to the root of the stories that are all around us, every day. ', 0),
(70, '9780091960292', 'Why Not Me?', 'Entertainment', 'Mindy Kaling', 'Ebury Publishing', 'Mindy has put the anxieties, the glamour and the celebrations of her second coming-of-age into this book, to which anyone can relate. (And, if they can\'t, they can skip to the parts where she talks about meeting Bradley Cooper.)', 9, 1, '2018-05-23', '2016-11-06', 'images/70.jpg', 'Mindy Kaling has found herself at a turning point. So in Why Not Me?, she shares her ongoing journey to find fulfilment and adventure in her adult life, be it falling in love at work, seeking new friendships in unlikely places, or attempting to be the first person in history to lose weight without any behaviour modification whatsoever.', 0),
(71, '9781787330726', 'Warlight', 'Romance', 'Michael Ondaatje', 'Vintage Publishing', '', 16, 9, '2018-05-23', '2018-06-07', 'images/71.jpg', 'In a narrative as mysterious as memory itself - at once both shadowed and luminous - Warlight is a vivid, thrilling novel of violence and love, intrigue and desire. It is 1945, and London is still reeling from the Blitz and years of war. 14-year-old Nathaniel and his sister, Rachel, are apparently abandoned by their parents, left in the care of an enigmatic figure named The Moth. They suspect he might be a criminal, and grow both more convinced and less concerned as they get to know his eccentric crew of friends: men and women with a shared history, all of whom seem determined now to protect, and educate (in rather unusual ways) Rachel and Nathaniel. But are they really what and who they claim to be? A dozen years later, Nathaniel begins to uncover all he didn\'t know or understand in that time, and it is this journey - through reality, recollection, and imagination - that is told in this magnificent novel. ', 0),
(72, '9781473629189', 'Legendary', 'Romance', 'Stephanie Garber', 'Hodder & Stoughton General Division', '\'I love this novel . . . It\'s a thing of beauty and the stuff of dreams\' Cecelia Ahern\r\n\r\n\'Immersive and engaging . . . destined to capture imaginations\' Kirkus\r\n\r\n\'An enchanting carnival of dreams and nightmares . . . beautifully and vividly written\' SciFi Now\r\n\r\n\'Stephanie Garber spins a spellbinding tale of sisterhood, love and betrayal . . . I lost myself in the dangerous, enchanting world she created - and never wanted to come out\' Sabaa Tahir\r\n', 19, 4, '2018-05-23', '2018-05-29', 'images/72.jpg', 'A heart to protect. A debt to repay. A game to win.\r\n\r\nAfter being swept up in the magical world of Caraval, Donatella Dragna has finally escaped her father and saved her sister Scarlett from a disastrous arranged marriage. The girls should be celebrating, but Tella isn\'t yet free. She made a desperate bargain with a mysterious criminal, and what Tella owes him no one has ever been able to deliver: Caraval Master Legend\'s true name.\r\n\r\nThe only chance of uncovering Legend\'s identity is to win Caraval, so Tella throws herself into the legendary competition once more - and into the path of the murderous heir to the throne, a doomed love story, and a web of secrets . . . including her sister\'s. Caraval has always demanded bravery, cunning, and sacrifice. But now the game is asking for more. If Tella can\'t fulfill her bargain and deliver Legend\'s name, she\'ll lose everything she cares about - maybe even her life. But if she wins, Legend and Caraval will be destroyed forever.\r\n\r\nWelcome, welcome to Caraval . . . the games have only just begun.', 0),
(73, '9781780622286', 'Six of Crows', 'Romance', 'Leigh Bardugo', 'Hachette Children\'s Group', 'Nominated for the CILIP Carnegie Medal 2017, this fantasy epic from the No. 1 NEW YORK TIMES bestselling author of the Grisha trilogy is gripping, sweeping and memorable - perfect for fans of George R. R. Martin, Laini Taylor and Kristin Cashore', 12, 6, '2018-05-23', '2016-06-02', 'images/73.jpg', 'Criminal prodigy Kaz Brekker is offered a chance at a deadly heist that could make him rich beyond his wildest dreams - but he can\'t pull it off alone. \r\n\r\nA convict with a thirst for revenge. \r\nA sharpshooter who can\'t walk away from a wager.\r\nA runaway with a privileged past. \r\nA spy known as the Wraith. \r\nA Heartrender using her magic to survive the slums. \r\nA thief with a gift for unlikely escapes. \r\n\r\nSix dangerous outcasts. One impossible heist. \r\n\r\nKaz\'s crew is the only thing that might stand between the world and destruction - if they don\'t kill each other first.', 0),
(74, '9780751550047', 'Two by Two', 'Romance', 'Nicholas Sparks', 'Little, Brown Book Group', 'From the author of The Notebook and See Me comes a beautiful story of heartbreak, strength and unconditional love that will capture your heart.\r\n\r\nSometimes the end is just the beginning . . .', 6, 3, '2018-05-23', '2017-06-01', 'images/74.jpg', 'Russell Green has it all: a loving family, a successful career and a beautiful house. But underneath his seemingly perfect world, cracks are beginning to appear . . . and no one is more surprised than Russ when the life he took for granted is turned upside down. \r\n\r\nFinding himself single-handedly caring for his young daughter, while trying to launch his own business, the only thing Russ knows is that he must shelter his little girl from the consequences of these changes. \r\n\r\nAs Russ embarks on this daunting and unexpected new chapter of his life, a chance encounter will challenge him to find a happiness beyond anything he could ever have imagine', 0),
(75, '9781471162589', 'Five Years From Now', 'Romance', 'Paige Toon', 'Simon & Schuster Ltd', '\r\n   \r\nFive Years From Now\r\n 4.48 (103 ratings by Goodreads)\r\nPaperback English\r\nBy (author)  Paige Toon\r\nShare    \r\n\'Tender, heartbreaking and magical . . . I went from feeling warm and fuzzy to shock, delight before, finally, well - you\'ll just have to read it!\'\r\nGIOVANNA FLETCHER\r\n\'Filled with warmth and poignancy, Five Years From Now is a page-turner and a delight\' JANE COSTELLO', 9, 10, '2018-05-23', '2018-05-17', 'images/75.jpg', 'What if you met the right person at the wrong time?\r\n\r\nNell and Van meet as children when their parents fall in love, but soon they are forced worlds apart.\r\n\r\nFive years later, they find each other. Their bond is rekindled and new feelings take hold, but once again they must separate.\r\n\r\nFor the next two decades, fate brings Nell and Van together every five years, as life and circumstance continue to divide them. Will they ever find true happiness? And will it be together?', 0),
(76, '9780241962138', 'The Course of Love', 'Romance', 'Alain de Botton', 'Penguin Books Ltd', 'A brilliant new novel about love and marriage in the modern world - from the author the bestselling novel Essays in Love\r\n', 10, 3, '2018-05-23', '0007-01-26', 'images/76.jpg', 'This is a love story with a difference. From dating to marriage, from having kids to having affairs, it follows the progress of a single ordinary relationship: tender, messy, hilarious, painful, and entirely un-Romantic. It is a love story for the modern world, chronicling the daily intimacies, the blazing rows, the endless tiny gestures that make up a life shared between two people. Moving and deeply insightful, The Course of Love offers us a window into essential truths about the nature of love.', 0),
(77, '9781760290788', 'China Rich Girlfriend', 'Romance', 'Kevin Kwan', 'Allen & Unwin', 'From the bestselling author of Crazy Rich Asians (Soon to be a MAJOR MOTION PICTURE starring Constance Wu, Henry Golding, Michelle Yeoh and Gemma Chan) comes a deliciously fun story of family, fortune, and fame in Mainland China.\r\n', 9, 6, '2018-05-23', '2016-07-19', 'images/77.jpg', 'On the eve of her wedding to Nicholas Young, heir to one of the greatest fortunes in Asia, Rachel should be over the moon. She has a flawless Asscher-cut diamond from JAR, a wedding dress she loves more than anything found in the salons of Paris, and a fiance willing to sacrifice his entire inheritance in order to marry her. But Rachel still mourns the fact that her birthfather, a man she never knew, won\'t be able to walk her down the aisle. Until: a shocking revelation draws Rachel into a world of Shanghai splendour beyond anything she has ever imagined.\r\n\r\nHere we meet Carlton, a Ferrari-crashing bad boy known for Prince Harry-like antics; Colette, a celebrity girlfriend chased by fevered paparazzi; and the man Rachel has spent her entire life waiting to meet: her father. Meanwhile, Singapore\'s It Girl, Astrid Leong, is shocked to discover that there is a downside to having a newly minted tech billionaire husband. A romp through Asia\'s most exclusive clubs, auction houses, and estates, China Rich Girlfriend brings us into the elite circles of Mainland China, introducing a captivating cast of characters, and offering an inside glimpse at what it\'s like to be gloriously, crazily, China-rich.', 0),
(78, '9781782393849', 'Crazy Rich Asians', 'Romance', 'Kevin Kwan', 'ATLANTIC BOOKS', '', 9, 3, '2018-05-23', '2014-05-20', 'images/78.jpg', 'When Rachel Chu agrees to spend the summer in Singapore with her boyfriend, Nicholas Young, she envisions a humble family home and time with the man she might one day marry. What she doesn\'t know is that Nick\'s family home happens to look like a palace, that she\'ll ride in more private planes than cars and that she is about to encounter the strangest, craziest group of people in existence. Uproarious, addictive, and filled with jaw-dropping opulence, Crazy Rich Asians is an insider\'s look at the Asian jet set; a perfect depiction of the clash between old money and new money - and a fabulous novel about what it means to be young, in love, and gloriously, crazily rich. ', 0),
(79, '9780718157838', 'Me Before You', 'Romance', 'Jojo Moyes', 'Penguin Books Ltd', '', 12, 5, '2018-05-23', '2015-09-02', 'images/79.jpg', 'Will needed Lou as much as she needed him, but will her love be enough to save his life?\r\n\r\nLou Clark knows lots of things. She knows how many footsteps there are between the bus stop and home. She knows she likes working in The Buttered Bun teashop and she knows she might not love her boyfriend Patrick. \r\n\r\nWhat Lou doesn\'t know is she\'s about to lose her job or that knowing what\'s coming is what keeps her sane. ', 0),
(80, '9781405909075', 'After You', 'Romance', 'Jojo Moyes', 'Penguin Books Ltd', 'THE SEQUEL TO THE GLOBAL PHENOMENON, ME BEFORE YOU\r\n\r\n\'Matches Me Before You. Funny, sad and wise, you\'ll be using a hankie as a bookmark\' Mail on Sunday\r\n\r\n\'Moyes totally delivers. With its twisty plot, characters you fall in love with, weepy bits and witty bits, this is pretty much perfect\' Glamour', 10, 1, '2018-05-23', '2016-09-15', 'images/80.jpg', 'Lou Clark has lots of questions.\r\n\r\nLike how it is she\'s ended up working in an airport bar, spending every shift watching other people jet off to new places.\r\n\r\nOr why the flat she\'s owned for a year still doesn\'t feel like home.\r\n\r\nWhether her close-knit family can forgive her for what she did eighteen months ago.\r\n\r\nAnd will she ever get over the love of her life.\r\n\r\nWhat Lou does know for certain is that something has to change.\r\n\r\nThen, one night, it does.\r\n\r\nBut does the stranger on her doorstep hold the answers Lou is searching for - or just more questions?\r\n\r\nClose the door and life continues: simple, ordered, safe.\r\n\r\nOpen it and she risks everything.\r\n\r\nBut Lou once made a promise to live. And if she\'s going to keep it, she has to invite them in . . .\r\n', 0);

-- --------------------------------------------------------

--
-- Table structure for table `log_history`
--

CREATE TABLE `log_history` (
  `log_id` int(11) NOT NULL,
  `log_date` datetime NOT NULL,
  `log_activity` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `log_history`
--

INSERT INTO `log_history` (`log_id`, `log_date`, `log_activity`) VALUES
(1, '2018-05-18 19:44:35', 'EDIT Book with an ISBN#: 123455'),
(2, '2018-05-18 20:47:41', 'Delete Book with an ISBN#: 213'),
(3, '2018-05-18 20:47:44', 'Delete Book with an ISBN#: 123131'),
(4, '2018-05-18 20:47:48', 'Delete Book with an ISBN#: 123455'),
(5, '2018-05-18 20:48:07', 'EDIT Book with an ISBN#: 9780141328294'),
(6, '2018-05-18 20:48:16', 'EDIT Book with an ISBN#: 9780141328294'),
(7, '2018-05-18 20:52:45', 'EDIT Book with an ISBN#: 9780141328294'),
(8, '2018-05-18 20:54:28', 'EDIT Book with an ISBN#: 9780141328294'),
(9, '2018-05-18 20:54:42', 'EDIT Book with an ISBN#: 9780141328294'),
(10, '2018-05-18 20:58:46', 'EDIT Book with an ISBN#: 9780141328294'),
(11, '2018-05-18 21:28:18', 'EDIT Book with an ISBN#: 9780141328294'),
(12, '2018-05-18 21:32:38', 'EDIT Book with an ISBN#: 9780141328294'),
(13, '2018-05-18 21:34:43', 'EDIT Book with an ISBN#: 9780141328294'),
(14, '2018-05-25 15:37:53', 'EDIT Book with an ISBN#: 9780963339744'),
(15, '2018-05-25 15:38:03', 'EDIT Book with an ISBN#: 9780963339744');

-- --------------------------------------------------------

--
-- Table structure for table `transact_details`
--

CREATE TABLE `transact_details` (
  `T_ID` int(11) NOT NULL,
  `T_QTY` int(11) NOT NULL,
  `T_TOTPRICE` double NOT NULL,
  `D_START` date NOT NULL,
  `D_END` date NOT NULL,
  `T_ISRETURNED` int(11) NOT NULL,
  `D_RETURN` date NOT NULL,
  `P_OVERDUE` int(11) NOT NULL,
  `B_ID` int(11) NOT NULL,
  `U_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `usr_details`
--

CREATE TABLE `usr_details` (
  `u_id` int(11) NOT NULL,
  `u_email` varchar(100) NOT NULL,
  `u_password` varchar(100) NOT NULL,
  `u_firstname` varchar(100) NOT NULL,
  `u_lastname` varchar(100) NOT NULL,
  `u_address` varchar(255) NOT NULL,
  `u_birthdate` varchar(30) NOT NULL,
  `u_type` varchar(10) NOT NULL,
  `u_valcode` text NOT NULL,
  `u_activate` tinyint(4) NOT NULL DEFAULT '0',
  `u_contactnum` int(11) DEFAULT NULL,
  `u_status` tinyint(4) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `usr_details`
--

INSERT INTO `usr_details` (`u_id`, `u_email`, `u_password`, `u_firstname`, `u_lastname`, `u_address`, `u_birthdate`, `u_type`, `u_valcode`, `u_activate`, `u_contactnum`, `u_status`) VALUES
(1, 'user_01@gmail.com', '123', 'John', 'Doe', 'Blk 23 San Mateo, New York Philippines', '10/31/1990', 'User', 'asdasndjasndasjdasjkdmasd', 0, 919544332, 0),
(2, 'user_02@gmail.com', '202cb962ac59075b964b07152d234b70', 'John', 'Doe', 'sasdasa', '2000-12-21', 'user', 'ef007769fecab02b489156df5806dc1d', 0, 2147483647, 0),
(3, 'user_03@gmail.com', '81dc9bdb52d04dc20036dbd8313ed055', 'Juan', 'Medina', 'asdasdasdasdadaasda', '2000-12-13', 'user', '4334888adb554142a743d4640c6aa372', 0, 2147483647, 0),
(4, 'user_04@gmail.com', '202cb962ac59075b964b07152d234b70', 'Juan', 'Medina', 'dsadasdasdasdasdas', '2000-12-21', 'user', 'f72e05ed3fedbde1b7acd33bc8378ac0', 0, 2147483647, 0),
(5, 'user_05@gmail.com', '202cb962ac59075b964b07152d234b70', 'Francis', 'Gella', 'sdasdasdasdajskdhasdjasdhnaskda', '2000-12-28', 'user', '20c85a7f909d0ea9fcc7f208b0511332', 0, 2147483647, 0),
(6, 'user_06@gmail.com', '202cb962ac59075b964b07152d234b70', 'Juan', 'Antonio', 'awwwwwwwwwwwwwwwww', '2000-12-21', 'user', '5c150b413ba16246a92c670079c9b417', 0, 2147483647, 0),
(7, 'user_07@gmail.com', '81dc9bdb52d04dc20036dbd8313ed055', 'Juan', 'Antonio', 'dasdasfasfasdas', '2000-12-21', 'user', '315003fe87895023896e3022ec714bf0', 0, 2147483647, 0),
(8, 'user_08@gmail.com', '202cb962ac59075b964b07152d234b70', 'Juan', 'Antonio', 'dasdsadasidasmdoa', '2000-12-05', 'user', 'eacc5efc0ec4034acfec5fc5adb93f1a', 0, 2147483647, 0),
(9, 'dasdasa@gmail.com', '202cb962ac59075b964b07152d234b70', 'john', 'nathaniel', 'asdasdasda', '2000-12-21', 'user', '0', 1, 2147483647, 0),
(10, 'user_09@gmail.com', '202cb962ac59075b964b07152d234b70', 'John', 'Doe', 'dasdasdajdahudiajhdadkajbdjakidjandgajdada', '2000-12-14', 'user', '2498b000a592e7bd96db7c47181d6b9a', 1, 2147483647, 0),
(11, 'gianestacio@gmail.com', '202cb962ac59075b964b07152d234b70', 'Gian', 'Estacio', 'akjdawhdkasdhasdhak', '1902-01-03', 'user', '0', 1, 2147483647, 0),
(12, 'adminako1@gmail.com', '81dc9bdb52d04dc20036dbd8313ed055', 'Uzumaki', 'Naruto', ' ', '', '1994-04-30', '22d6947c166ab722d111288df0b16bb8', 0, 2147483647, 0),
(13, 'adminako1@gmail.com', '202cb962ac59075b964b07152d234b70', 'Uzumaki', 'Naruto', '', '1994-04-30', ' ', '0', 127, 0, 0),
(14, 'adminako1@gmail.com', '202cb962ac59075b964b07152d234b70', 'Uzumakia', 'Narutoa', '', '1996-07-30', ' ', '0', 127, 0, 0),
(15, 'adminako1@gmail.com', '202cb962ac59075b964b07152d234b70', 'admin', 'ako', '1920-02-02', 'admin', ' ', '0', 127, 0, 0),
(16, 'adminako1@gmail.com', '202cb962ac59075b964b07152d234b70', 'sdads', 'asdasda', ' ', '1920-02-02', 'admin', ' ', 0, 2147483647, 0),
(17, 'adminako2@gmail.com', '202cb962ac59075b964b07152d234b70', 'sdads', 'asdasda', ' ', '1920-02-02', 'admin', ' ', 0, 2147483647, 0),
(18, 'admin01@gmail.com', '81dc9bdb52d04dc20036dbd8313ed055', 'Alpha', 'Admin', ' ', '1998-12-17', 'admin', ' ', 0, 2147483647, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `book_details`
--
ALTER TABLE `book_details`
  ADD PRIMARY KEY (`B_ID`);

--
-- Indexes for table `log_history`
--
ALTER TABLE `log_history`
  ADD PRIMARY KEY (`log_id`);

--
-- Indexes for table `transact_details`
--
ALTER TABLE `transact_details`
  ADD PRIMARY KEY (`T_ID`),
  ADD KEY `B_ID` (`B_ID`),
  ADD KEY `U_ID` (`U_id`);

--
-- Indexes for table `usr_details`
--
ALTER TABLE `usr_details`
  ADD PRIMARY KEY (`u_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `book_details`
--
ALTER TABLE `book_details`
  MODIFY `B_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=81;

--
-- AUTO_INCREMENT for table `log_history`
--
ALTER TABLE `log_history`
  MODIFY `log_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT for table `transact_details`
--
ALTER TABLE `transact_details`
  MODIFY `T_ID` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `usr_details`
--
ALTER TABLE `usr_details`
  MODIFY `u_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
